#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLevelImport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SunriseHR")]
	public partial class HrDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertTAXLVL(TAXLVL instance);
    partial void UpdateTAXLVL(TAXLVL instance);
    partial void DeleteTAXLVL(TAXLVL instance);
    partial void InsertTAXLVL1(TAXLVL1 instance);
    partial void UpdateTAXLVL1(TAXLVL1 instance);
    partial void DeleteTAXLVL1(TAXLVL1 instance);
    #endregion
		
		public HrDBDataContext() : 
				base(global::TaxLevelImport.Properties.Settings.Default.SunriseHRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HrDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HrDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HrDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HrDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TAXLVL> TAXLVL
		{
			get
			{
				return this.GetTable<TAXLVL>();
			}
		}
		
		public System.Data.Linq.Table<TAXLVL1> TAXLVL1
		{
			get
			{
				return this.GetTable<TAXLVL1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAXLVL")]
	public partial class TAXLVL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _YEAR;
		
		private decimal _AMT_H;
		
		private decimal _AMT_L;
		
		private decimal _PER0;
		
		private decimal _PER1;
		
		private decimal _PER2;
		
		private decimal _PER3;
		
		private decimal _PER4;
		
		private decimal _PER5;
		
		private decimal _PER6;
		
		private decimal _PER7;
		
		private decimal _PER8;
		
		private decimal _PER9;
		
		private decimal _PER10;
		
		private decimal _PER11;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    partial void OnAMT_HChanging(decimal value);
    partial void OnAMT_HChanged();
    partial void OnAMT_LChanging(decimal value);
    partial void OnAMT_LChanged();
    partial void OnPER0Changing(decimal value);
    partial void OnPER0Changed();
    partial void OnPER1Changing(decimal value);
    partial void OnPER1Changed();
    partial void OnPER2Changing(decimal value);
    partial void OnPER2Changed();
    partial void OnPER3Changing(decimal value);
    partial void OnPER3Changed();
    partial void OnPER4Changing(decimal value);
    partial void OnPER4Changed();
    partial void OnPER5Changing(decimal value);
    partial void OnPER5Changed();
    partial void OnPER6Changing(decimal value);
    partial void OnPER6Changed();
    partial void OnPER7Changing(decimal value);
    partial void OnPER7Changed();
    partial void OnPER8Changing(decimal value);
    partial void OnPER8Changed();
    partial void OnPER9Changing(decimal value);
    partial void OnPER9Changed();
    partial void OnPER10Changing(decimal value);
    partial void OnPER10Changed();
    partial void OnPER11Changing(decimal value);
    partial void OnPER11Changed();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    #endregion
		
		public TAXLVL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT_H", DbType="Decimal(16,2) NOT NULL", IsPrimaryKey=true)]
		public decimal AMT_H
		{
			get
			{
				return this._AMT_H;
			}
			set
			{
				if ((this._AMT_H != value))
				{
					this.OnAMT_HChanging(value);
					this.SendPropertyChanging();
					this._AMT_H = value;
					this.SendPropertyChanged("AMT_H");
					this.OnAMT_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT_L", DbType="Decimal(16,2) NOT NULL")]
		public decimal AMT_L
		{
			get
			{
				return this._AMT_L;
			}
			set
			{
				if ((this._AMT_L != value))
				{
					this.OnAMT_LChanging(value);
					this.SendPropertyChanging();
					this._AMT_L = value;
					this.SendPropertyChanged("AMT_L");
					this.OnAMT_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER0", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER0
		{
			get
			{
				return this._PER0;
			}
			set
			{
				if ((this._PER0 != value))
				{
					this.OnPER0Changing(value);
					this.SendPropertyChanging();
					this._PER0 = value;
					this.SendPropertyChanged("PER0");
					this.OnPER0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER1", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER1
		{
			get
			{
				return this._PER1;
			}
			set
			{
				if ((this._PER1 != value))
				{
					this.OnPER1Changing(value);
					this.SendPropertyChanging();
					this._PER1 = value;
					this.SendPropertyChanged("PER1");
					this.OnPER1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER2", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER2
		{
			get
			{
				return this._PER2;
			}
			set
			{
				if ((this._PER2 != value))
				{
					this.OnPER2Changing(value);
					this.SendPropertyChanging();
					this._PER2 = value;
					this.SendPropertyChanged("PER2");
					this.OnPER2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER3", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER3
		{
			get
			{
				return this._PER3;
			}
			set
			{
				if ((this._PER3 != value))
				{
					this.OnPER3Changing(value);
					this.SendPropertyChanging();
					this._PER3 = value;
					this.SendPropertyChanged("PER3");
					this.OnPER3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER4", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER4
		{
			get
			{
				return this._PER4;
			}
			set
			{
				if ((this._PER4 != value))
				{
					this.OnPER4Changing(value);
					this.SendPropertyChanging();
					this._PER4 = value;
					this.SendPropertyChanged("PER4");
					this.OnPER4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER5", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER5
		{
			get
			{
				return this._PER5;
			}
			set
			{
				if ((this._PER5 != value))
				{
					this.OnPER5Changing(value);
					this.SendPropertyChanging();
					this._PER5 = value;
					this.SendPropertyChanged("PER5");
					this.OnPER5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER6", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER6
		{
			get
			{
				return this._PER6;
			}
			set
			{
				if ((this._PER6 != value))
				{
					this.OnPER6Changing(value);
					this.SendPropertyChanging();
					this._PER6 = value;
					this.SendPropertyChanged("PER6");
					this.OnPER6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER7", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER7
		{
			get
			{
				return this._PER7;
			}
			set
			{
				if ((this._PER7 != value))
				{
					this.OnPER7Changing(value);
					this.SendPropertyChanging();
					this._PER7 = value;
					this.SendPropertyChanged("PER7");
					this.OnPER7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER8", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER8
		{
			get
			{
				return this._PER8;
			}
			set
			{
				if ((this._PER8 != value))
				{
					this.OnPER8Changing(value);
					this.SendPropertyChanging();
					this._PER8 = value;
					this.SendPropertyChanged("PER8");
					this.OnPER8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER9", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER9
		{
			get
			{
				return this._PER9;
			}
			set
			{
				if ((this._PER9 != value))
				{
					this.OnPER9Changing(value);
					this.SendPropertyChanging();
					this._PER9 = value;
					this.SendPropertyChanged("PER9");
					this.OnPER9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER10", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER10
		{
			get
			{
				return this._PER10;
			}
			set
			{
				if ((this._PER10 != value))
				{
					this.OnPER10Changing(value);
					this.SendPropertyChanging();
					this._PER10 = value;
					this.SendPropertyChanged("PER10");
					this.OnPER10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER11", DbType="Decimal(16,2) NOT NULL")]
		public decimal PER11
		{
			get
			{
				return this._PER11;
			}
			set
			{
				if ((this._PER11 != value))
				{
					this.OnPER11Changing(value);
					this.SendPropertyChanging();
					this._PER11 = value;
					this.SendPropertyChanged("PER11");
					this.OnPER11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAXLVL")]
	public partial class TAXLVL1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _YEAR;
		
		private double _AMT_H;
		
		private double _AMT_L;
		
		private double _PER0;
		
		private double _PER1;
		
		private double _PER2;
		
		private double _PER3;
		
		private double _PER4;
		
		private double _PER5;
		
		private double _PER6;
		
		private double _PER7;
		
		private double _PER8;
		
		private double _PER9;
		
		private double _PER10;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    partial void OnAMT_HChanging(double value);
    partial void OnAMT_HChanged();
    partial void OnAMT_LChanging(double value);
    partial void OnAMT_LChanged();
    partial void OnPER0Changing(double value);
    partial void OnPER0Changed();
    partial void OnPER1Changing(double value);
    partial void OnPER1Changed();
    partial void OnPER2Changing(double value);
    partial void OnPER2Changed();
    partial void OnPER3Changing(double value);
    partial void OnPER3Changed();
    partial void OnPER4Changing(double value);
    partial void OnPER4Changed();
    partial void OnPER5Changing(double value);
    partial void OnPER5Changed();
    partial void OnPER6Changing(double value);
    partial void OnPER6Changed();
    partial void OnPER7Changing(double value);
    partial void OnPER7Changed();
    partial void OnPER8Changing(double value);
    partial void OnPER8Changed();
    partial void OnPER9Changing(double value);
    partial void OnPER9Changed();
    partial void OnPER10Changing(double value);
    partial void OnPER10Changed();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    #endregion
		
		public TAXLVL1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT_H", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double AMT_H
		{
			get
			{
				return this._AMT_H;
			}
			set
			{
				if ((this._AMT_H != value))
				{
					this.OnAMT_HChanging(value);
					this.SendPropertyChanging();
					this._AMT_H = value;
					this.SendPropertyChanged("AMT_H");
					this.OnAMT_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT_L", DbType="Float NOT NULL")]
		public double AMT_L
		{
			get
			{
				return this._AMT_L;
			}
			set
			{
				if ((this._AMT_L != value))
				{
					this.OnAMT_LChanging(value);
					this.SendPropertyChanging();
					this._AMT_L = value;
					this.SendPropertyChanged("AMT_L");
					this.OnAMT_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER0", DbType="Float NOT NULL")]
		public double PER0
		{
			get
			{
				return this._PER0;
			}
			set
			{
				if ((this._PER0 != value))
				{
					this.OnPER0Changing(value);
					this.SendPropertyChanging();
					this._PER0 = value;
					this.SendPropertyChanged("PER0");
					this.OnPER0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER1", DbType="Float NOT NULL")]
		public double PER1
		{
			get
			{
				return this._PER1;
			}
			set
			{
				if ((this._PER1 != value))
				{
					this.OnPER1Changing(value);
					this.SendPropertyChanging();
					this._PER1 = value;
					this.SendPropertyChanged("PER1");
					this.OnPER1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER2", DbType="Float NOT NULL")]
		public double PER2
		{
			get
			{
				return this._PER2;
			}
			set
			{
				if ((this._PER2 != value))
				{
					this.OnPER2Changing(value);
					this.SendPropertyChanging();
					this._PER2 = value;
					this.SendPropertyChanged("PER2");
					this.OnPER2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER3", DbType="Float NOT NULL")]
		public double PER3
		{
			get
			{
				return this._PER3;
			}
			set
			{
				if ((this._PER3 != value))
				{
					this.OnPER3Changing(value);
					this.SendPropertyChanging();
					this._PER3 = value;
					this.SendPropertyChanged("PER3");
					this.OnPER3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER4", DbType="Float NOT NULL")]
		public double PER4
		{
			get
			{
				return this._PER4;
			}
			set
			{
				if ((this._PER4 != value))
				{
					this.OnPER4Changing(value);
					this.SendPropertyChanging();
					this._PER4 = value;
					this.SendPropertyChanged("PER4");
					this.OnPER4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER5", DbType="Float NOT NULL")]
		public double PER5
		{
			get
			{
				return this._PER5;
			}
			set
			{
				if ((this._PER5 != value))
				{
					this.OnPER5Changing(value);
					this.SendPropertyChanging();
					this._PER5 = value;
					this.SendPropertyChanged("PER5");
					this.OnPER5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER6", DbType="Float NOT NULL")]
		public double PER6
		{
			get
			{
				return this._PER6;
			}
			set
			{
				if ((this._PER6 != value))
				{
					this.OnPER6Changing(value);
					this.SendPropertyChanging();
					this._PER6 = value;
					this.SendPropertyChanged("PER6");
					this.OnPER6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER7", DbType="Float NOT NULL")]
		public double PER7
		{
			get
			{
				return this._PER7;
			}
			set
			{
				if ((this._PER7 != value))
				{
					this.OnPER7Changing(value);
					this.SendPropertyChanging();
					this._PER7 = value;
					this.SendPropertyChanged("PER7");
					this.OnPER7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER8", DbType="Float NOT NULL")]
		public double PER8
		{
			get
			{
				return this._PER8;
			}
			set
			{
				if ((this._PER8 != value))
				{
					this.OnPER8Changing(value);
					this.SendPropertyChanging();
					this._PER8 = value;
					this.SendPropertyChanged("PER8");
					this.OnPER8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER9", DbType="Float NOT NULL")]
		public double PER9
		{
			get
			{
				return this._PER9;
			}
			set
			{
				if ((this._PER9 != value))
				{
					this.OnPER9Changing(value);
					this.SendPropertyChanging();
					this._PER9 = value;
					this.SendPropertyChanged("PER9");
					this.OnPER9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER10", DbType="Float NOT NULL")]
		public double PER10
		{
			get
			{
				return this._PER10;
			}
			set
			{
				if ((this._PER10 != value))
				{
					this.OnPER10Changing(value);
					this.SendPropertyChanging();
					this._PER10 = value;
					this.SendPropertyChanged("PER10");
					this.OnPER10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
